# Generated by Django 5.2.5 on 2025-08-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_on', '-updated_on']},
        ),
    ]
