# Generated by Django 5.2.5 on 2025-08-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_on', '-updated_on']},
        ),
    ]
